[book]
authors = ["Denys Vuika"]
language = "en"
multilingual = false
src = "src"
title = "Taco Book"

[output.html]
git-repository-url = "https://github.com/tacogram/taco-book"
site-url = "/taco-book/"
